#!/usr/bin/env bash

# Power menu options
options="Sleep\nReboot\nPoweroff"

# Show rofi menu and get selection
chosen=$(echo -e "$options" | rofi -dmenu -i -p "Power Menu" \
    -theme ~/.config/rofi/tokyonight.rasi \
    -theme-str 'window {width: 15%;} entry {enabled: false;} listview {lines: 3;}')

# Execute the selected action
case "$chosen" in
    "Sleep")
        systemctl suspend
        ;;
    "Reboot")
        systemctl reboot
        ;;
    "Poweroff")
        systemctl poweroff
        ;;
    *)
        exit 1
        ;;
esac
