#!/usr/bin/env bash

# Browser options
options="Chromium
Brave"

# Show rofi menu
chosen=$(echo -e "$options" | rofi -dmenu -i -p "Browser" \
    -theme-str 'window {width: 10%;} listview {lines: 2;}')

# Exit if nothing selected
[ -z "$chosen" ] && exit 0

# Launch selected browser
case "$chosen" in
    "Chromium")
        chromium &
        ;;
    "Brave")
        brave &
        ;;
esac
